# Generated by Django 3.0.4 on 2021-01-14 00:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='History',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('verb', models.CharField(max_length=50)),
                ('question', models.BooleanField()),
                ('negative', models.BooleanField()),
                ('affix', models.CharField(max_length=10)),
                ('morph', models.CharField(max_length=10)),
                ('tense', models.CharField(max_length=20)),
                ('created_at', models.DateTimeField(auto_now=True)),
            ],
        ),
    ]
