# Generated by Django 3.0.4 on 2021-01-16 23:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='history',
            options={'verbose_name_plural': 'History'},
        ),
        migrations.AddField(
            model_name='history',
            name='noun',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AddField(
            model_name='history',
            name='proper_noun',
            field=models.BooleanField(default=False),
        ),
    ]
