# Generated by Django 5.2.7 on 2025-10-22 07:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ui', '0002_auto_20210117_0059'),
    ]

    operations = [
        migrations.AlterField(
            model_name='history',
            name='negative',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='history',
            name='question',
            field=models.BooleanField(default=False),
        ),
    ]
