ENGLISH_TO_TURKISH = {
    'accept': 'kabul et',
    'achieve': 'başar',
    'act': 'davran',
    'add': 'ekle',
    'admit': 'itiraf et',
    'advise': 'öner',
    'affect': 'etkile',
    'agree': 'katıl',
    'allow': 'izin ver',
    'answer': 'cevap ver',
    'appeal': 'başvur',
    'appear': 'ortaya çık',
    'apply': 'uygula',
    'appoint': 'tayin et',
    'approve': 'onayla',
    'argue': 'tartış',
    'arrange': 'düzenle',
    'arrest': 'tutukla',
    'arrive': 'ulaş',
    'ask': 'sor',
    'attack': 'saldır',
    'avoid': 'kaçın',
    'be': 'ol',
    'beat': 'döv',
    'become': 'hâline gel',
    'begin': 'başla',
    'believe': 'inan',
    'belong': 'ait ol',
    'bite': 'ısır',
    'blame': 'suçla',
    'bleed': 'kana',
    'blow': 'üfle',
    'born': 'doğ',
    'break': 'kır',
    'bring': 'getir',
    'build': 'inşa et',
    'burn': 'yan',
    'buy': 'satın al',
    'calculate': 'hesapla',
    'call': 'ara',
    'can': 'yapabil',
    'care': 'önemse',
    'carry': 'taşı',
    'catch': 'yakala',
    'cause': 'neden ol',
    'change': 'değiştir',
    'check': 'kontrol et',
    'choose': 'seç',
    'clean': 'temizle',
    'climb': 'tırman',
    'collect': 'biriktir',
    'come': 'gel',
    'comment': 'yorumla',
    'complain': 'şikâyet et',
    'complete': 'tamamla',
    'confirm': 'doğrula',
    'consider': 'düşün',
    'contact': 'temasa geç',
    'continue': 'devam et',
    'cook': 'pişir',
    'copy': 'kopyala',
    'cost': 'mal ol',
    'count': 'say',
    'cover': 'kapla',
    'create': 'yarat',
    'cry': 'ağla',
    'cut': 'kes',
    'dance': 'dans et',
    'deal': 'anlaş',
    'decide': 'karar ver',
    'deliver': 'teslim et',
    'deny': 'inkâr et',
    'describe': 'tanımla',
    'design': 'tasarla',
    'destroy': 'yık',
    'develop': 'geliştir',
    'die': 'öl',
    'dig': 'kaz',
    'direct': 'yönelt',
    'disappear': 'ortadan kaybol',
    'discover': 'keşfet',
    'discuss': 'tartış',
    'disturb': 'rahatsız ',
    'devorce': 'ayrıl',
    'do': 'yap',
    'draw': 'çiz',
    'dream': 'hayal et',
    'dress': 'giyin',
    'drink': 'iç',
    'drive': 'sür',
    'eat': 'ye',
    'end': 'bitir',
    'enjoy': 'keyif al',
    'enter': 'gir',
    'escape': 'kaç',
    'examine': 'incele',
    'exercise': 'egzersiz yap',
    'exist': 'var ol',
    'expect': 'um',
    'explain': 'açıkla',
    'fail': 'başarısızlığa uğra',
    'fall': 'düş',
    'fear': 'kork',
    'feed': 'besle',
    'feel': 'hisset',
    'fight': 'kavga et',
    'fill': 'doldur',
    'find': 'bul',
    'finish': 'bitir',
    'fix': 'tamir et',
    'fly': 'uç',
    'follow': 'takip et',
    'forbid': 'yasakla',
    'forget': 'unut',
    'forgive': 'affet',
    'freeze': 'don',
    'get': 'al',
    'give': 'ver',
    'glow': 'parla',
    'go': 'git',
    'greet': 'karşıla',
    'grow': 'büyü',
    'guard': 'koru',
    'guess': 'tahmin et',
    'hang': 'as',
    'happen': 'meydana gel',
    'have': 'sahip ol',
    'hate': 'nefret et',
    'hear': 'duy',
    'help': 'yardım et',
    'hide': 'saklan',
    'hit': 'çarp',
    'hold': 'tut',
    'hope': 'umut et',
    'join': 'katıl',
    'joke': 'şaka yap',
    'judge': 'yargıla',
    'jump': 'zıpla',
    'keep': 'tut',
    'kick': 'tekmele',
    'kill': 'öldür',
    'kiss': 'öp',
    'knock': 'vur',
    'know': 'bil',
    'laugh': 'gül',
    'lay': 'yatır',
    'lead': 'öncülük et',
    'learn': 'öğren',
    'leave': 'ayrıl',
    'let': 'izin ver',
    'lie': 'yalan söyle',
    'lift': 'kaldır',
    'light': 'yak',
    'like': 'hoşlan',
    'list': 'sırala',
    'listen': 'dinle',
    'live': 'yaşa',
    'load': 'yükle',
    'lock': 'kilitle',
    'look': 'bak',
    'lose': 'kaybet',
    'love': 'sev',
    'make': 'yap',
    'manage': 'yönet',
    'mark': 'işaretle',
    'marry': 'evlen',
    'match': 'eşleştir',
    'may': 'olabil',
    'mean': 'kastet',
    'measure': 'ölç',
    'meet': 'buluş',
    'melt': 'eri',
    'mind': 'önemse',
    'miss': 'kaçır',
    'mix': 'karıştır',
    'move': 'hareket et',
    'must': 'gerekli ol',
    'need': 'ihtiyacı ol',
    'note': 'not et',
    'notice': 'farkına var',
    'obey': 'itaat et',
    'offer': 'teklif et',
    'open': 'aç',
    'order': 'sipariş ver',
    'own': 'sahip ol',
    'pack': 'bavul topla',
    'paint': 'boya',
    'pass': 'geç',
    'pause': 'ara ver',
    'pay': 'öde',
    'pick': 'topla',
    'plan': 'planla',
    'plant': 'dikmek',
    'play': 'oyna',
    'point': 'göster',
    'practise': 'alıştır',
    'pray': 'dua et',
    'prefer': 'tercih et',
    'prepare': 'hazırla',
    'present': 'sun',
    'press': 'bas',
    'produce': 'üret',
    'promise': 'söz ver',
    'propose': 'teklif et',
    'protect': 'koru',
    'protest': 'protesto et',
    'prove': 'kanıtla',
    'provide': 'sağla',
    'pull': 'çek',
    'push': 'it',
    'put': 'koy',
    'race': 'yarış',
    'reach': 'ulaş',
    'read': 'oku',
    'realize': 'farkına var',
    'recall': 'hatırla',
    'recognise': 'tanı',
    'record': 'kayda geçir',
    'refuse': 'reddet',
    'release': 'serbest bırak',
    'remember': 'hatırla',
    'remind': 'hatırla',
    'repeat': 'tekrarla',
    'reply': 'yanıtla',
    'report': 'bildir',
    'restore': 'yenile',
    'return': 'geri dön',
    'ride': 'bin',
    'ring': 'çal',
    'rise': 'yüksel',
    'run': 'koş',
    'save': 'kaydet',
    'say': 'söyle',
    'search': 'ara',
    'secure': 'koru',
    'see': 'gör',
    'seem': 'görün',
    'sell': 'sat',
    'send': 'gönder',
    'separate': 'ayır',
    'serve': 'hizmet et',
    'set': 'ayarla',
    'settle': 'yerleş',
    'shake': 'salla',
    'share': 'paylaş',
    'shine': 'parla',
    'show': 'göster',
    'shoot': 'vur',
    'shout': 'bağır',
    'shut': 'kapat',
    'sign': 'imzala',
    'sing': 'şarkı söyle',
    'sit': 'otur',
    'ski': 'kayak yap',
    'sleep': 'uyu',
    'slip': 'kay',
    'smile': 'gül',
    'solve': 'çöz',
    'sound': 'ses çıkar',
    'speak': 'konuş',
    'spend': 'harca',
    'spread': 'yayıl',
    'stand': 'ayakta dur',
    'start': 'başla',
    'stay': 'kal',
    'steal': 'çal',
    'step': 'adım at',
    'stick': 'yapış',
    'stop': 'dur',
    'study': 'çalış',
    'succeed': 'başarılı ol',
    'suffer': 'acı çek',
    'suggest': 'öner',
    'support': 'destekle',
    'survive': 'hayatta kal',
    'swear': 'küfret',
    'sweep': 'süpür',
    'swim': 'yüz',
    'switch': 'değiştir',
    'take': 'al',
    'talk': 'konuş',
    'taste': 'tat',
    'teach': 'öğret',
    'tear': 'yırt',
    'tell': 'anlat',
    'thank': 'teşekkür et',
    'think': 'düşün',
    'throw': 'fırlat',
    'tie': 'bağla',
    'touch': 'dokun',
    'travel': 'seyahat et',
    'try': 'dene',
    'turn': 'döndür',
    'understand': 'anla',
    'update': 'güncelleştir',
    'use': 'kullan',
    'view': 'görüntüle',
    'visit': 'ziyaret et',
    'vote': 'oy ver',
    'wait': 'bekle',
    'wake': 'uyan',
    'walk': 'yürü',
    'want': 'iste',
    'warn': 'uyar',
    'wash': 'yıka',
    'watch': 'izle',
    'wear': 'giy',
    'welcome': 'karşıla',
    'win': 'kazan',
    'wish': 'iste',
    'wonder': 'merak et',
    'work': 'çalış',
    'worry': 'endişelen',
    'write': 'yaz',
    'yawn': 'esne'
}